name: sqljocky
version: 0.4.4
author: James Ots <code@jamesots.com>
description: A MySQL connector
homepage: https://github.com/jamesots/sqljocky
documentation: http://jamesots.github.io/sqljocky/docs
environment:
  sdk: '>=0.5.1'
dependencies:
  unittest: '>=0.3.1+1'
  options_file: '>=0.9.11'
  logging: '>=0.3.1+1'
